name: Awesome Work Flow
on: 
  push:
  workflow_dispatch:
jobs:
  cool_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: First list the repo
        run: ls
      - name: Then checkout the repo
        uses: actions/checkout@v3
      - name: Then list the repo again
        run: ls
      - name: Compile this code
        run: c++ -o hello hello.cpp
      - name: Run this code
        run: ./hello
  detect_cpp_info:
    runs-on: ubuntu-latest
    steps:
      - name: run this command
        run: c++ --version
  manual_trigger_error:
    runs-on: ubuntu-latest
    steps:
      - name: trigger error
        run: echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"