name: Awesome Work Flow
on: push
jobs:
  cool_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: First list the repo
        run: ls
      - name: Then checkout the repo
        uses: actions/checkout@v3
      - name: Then list the repo again
        run: ls
      - name: Compile this code
        run: c++ -o hello hello.cpp
      - name: Run this code
        run: ./hello